default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: popular_restaurants_db
  username: postgres
  password: admin
  host: localhost
  port: 5432

test:
  <<: *default
  database: popular_restaurants_db
  username: postgres
  password: admin

production:
  <<: *default
  database: popular_restaurants_db
  username: postgres
  password: admin
